# SecureBank Production Docker Image

FROM python:3.12-slim


WORKDIR /app


COPY ../application/backend/requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY ../application/backend .


# Create non-root user

RUN useradd -m bankuser


USER bankuser


EXPOSE 5000


CMD ["python","app.py"]
