apiVersion: apps/v1
kind: Deployment

metadata:
  name: securebank
  namespace: securebank

spec:
  replicas: 4

  selector:
    matchLabels:
      app: securebank

  template:

    metadata:
      labels:
        app: securebank

    spec:

      ##################################
      # Main Container
      ##################################

      containers:

      - name: securebank

        image: rvsivakrishna/securebank:v3

        imagePullPolicy: Always

        ports:

        - containerPort: 8080

        env:

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: securebank-config
              key: DB_HOST

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: securebank-config
              key: DB_PORT

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: securebank-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: securebank-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: securebank-secret
              key: DB_PASSWORD

        ##################################
        # Readiness Probe
        ##################################

        readinessProbe:

          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 15
          periodSeconds: 10

        ##################################
        # Liveness Probe
        ##################################

        livenessProbe:

          httpGet:
            path: /health
            port: 8080

          initialDelaySeconds: 30
          periodSeconds: 20
